from pydantic import BaseModel, ConfigDict, Field


class ProductBase(BaseModel):
    name: str = Field(min_length=1, max_length=100, examples=["Monitor"])
    description: str = Field(max_length=500, examples=["27-inch 4K monitor"])
    price: float = Field(ge=0, examples=[299.99])
    quantity: int = Field(ge=0, examples=[15])


class ProductCreate(ProductBase):
    """Request body for POST and PUT. The ID is generated by the server."""


class ProductUpdate(BaseModel):
    """Request body for PATCH. Only the fields that are sent get changed."""

    name: str | None = Field(default=None, min_length=1, max_length=100)
    description: str | None = Field(default=None, max_length=500)
    price: float | None = Field(default=None, ge=0)
    quantity: int | None = Field(default=None, ge=0)


class ProductResponse(ProductBase):
    model_config = ConfigDict(from_attributes=True)

    id: int = Field(examples=[5])
    user_id: int = Field(description="ID of the user who owns this product", examples=[1])


class RootResponse(BaseModel):
    message: str
    version: str
    docs: str
    health: str


class HealthResponse(BaseModel):
    status: str


class ErrorResponse(BaseModel):
    detail: str


class UserCreate(BaseModel):
    username: str = Field(min_length=3, max_length=50, examples=["alice"])
    password: str = Field(min_length=8, max_length=128, examples=["a-strong-password"])


class UserResponse(BaseModel):
    id: int
    username: str


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class DeleteAllResponse(BaseModel):
    deleted: int
